services:
  homepage:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      HOMEPAGE_ALLOWED_HOSTS: homepage.alexpaquette.dev
    volumes:
      - ./config:/app/config
      - /opt/homepage/config/icons:/app/public/icons:ro
