services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command: serve
    volumes:
      - ./config:/etc/ntfy
      - ./data:/var/cache/ntfy
    ports:
      - "127.0.0.1:8093:80"
